### ISSUE TITLE
代码发布时间咨询

### ISSUE THREAD

**Issue by tom155680** [Haoyu-ha/ALMT#2]
尊敬的作者您好，有幸看到了您在EMNLP发表的这篇论文，我对此非常感兴趣，冒昧问下作者什么时候会开源代码？期待您的回复！

**Comment by Haoyu-ha** [comment]
感谢您对我们的研究工作的兴趣，我暂时先把模型的实现相关的源码上传上来了，希望对你有帮助。后面我会尽快完成代码的整理工作，并添加必要的注释。

**Comment by Haoyu-ha** [comment]
完整代码已公开，感谢您的关注！
