### ISSUE TITLE
最优指标对应的模型

### ISSUE THREAD

**Issue by cyang810** [Haoyu-ha/ALMT#4]
作者您好，感谢您开源您的工作。注意到代码中epoch设置为200，想问问论文中的指标是最后一轮test数据集的结果吗？还是200轮中表现最好的那一轮的结果？

**Comment by Haoyu-ha** [comment]
表现最好的。实际上到了后期模型会过拟合严重，提前停止就行。

**Comment by cyang810** [comment]
好的，非常感谢您的回复！
