### ISSUE TITLE
不同的数据集怎么训练

### ISSUE THREAD

**Issue by guoping1127** [Haoyu-ha/ALMT#7]
mosi和mosei这两个数据集合上面要采取相同的参数去跑吗？同样的采用变量去取实验数值吗？比如mosi中取最大的acc2的随机种子是38，mosei也要是38吗？

**Comment by Haoyu-ha** [comment]
你好。是相同的参数，但你也可以自己调整。关于随机数种子，这个取决你，你也可以将ALMT运行于与自己的方法同样的随机数种子设置下。整体上，只要是合理的对比，参数设置通常比较灵活。
